{% set name = "yamale" %}
{% set version = "3.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b1326b1f161cca5a84a0ebf638718647121aaff5e2ff9b3f99396a990b7b285

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - yamale = yamale.command_line:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - yamale
  commands:
    - yamale -h

about:
  home: https://github.com/23andMe/Yamale
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A schema and validator for YAML.
  description: |
    A schema and validator for YAML.
  doc_url: https://github.com/23andMe/Yamale
  dev_url: https://github.com/23andMe/Yamale

extra:
  recipe-maintainers:
    - adament
