{% set name = "yamale" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11758648080820a7cc3ab1b679cc88e5a37ab1a73c55202341c316eeb5e63274

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - yamale = yamale.command_line:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml

test:
  imports:
    - yamale
  commands:
    - yamale -h

about:
  home: https://github.com/23andMe/Yamale
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A schema and validator for YAML.
  description: |
    A schema and validator for YAML.
  doc_url: https://github.com/23andMe/Yamale
  dev_url: https://github.com/23andMe/Yamale

extra:
  recipe-maintainers:
    - adament
